### ISSUE TITLE
Refmaps Not Generating on ‘with-kotlin’ Branch

### ISSUE THREAD

**Issue by CanadianBaconBoi** [CubeSugarCheese/architectury-template-kotlin-dsl#1]
When compiling with the `with-kotlin` branch, refmaps are not bundled into the compiled jar files. Refmaps are generated on the `main` branch however.

**Comment by CubeSugarCheese** [comment]
> When compiling with the `with-kotlin` branch, refmaps are not bundled into the compiled jar files. Refmaps are generated on the `main` branch however.

fixed
that's because mixin not support to writedown using kotlin.
https://github.com/SpongePowered/Mixin/issues/245
